name: odm
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1
  firebase_messaging: ^12.0.0
  flutter_local_notifications: ^9.7.0
  firebase_storage: ^10.3.1
  firebase_storage_web: ^3.2.19
  get: ^4.6.5
  get_storage: ^2.0.3
  intl: ^0.17.0
  flutter_svg: ^0.23.0+1
  flutter_html: ^2.2.1
  expandable: ^5.0.1
  http: ^0.13.4
  http_interceptor: ^1.0.2
  google_sign_in: ^5.4.0
  kakao_flutter_sdk_user: ^1.2.1
  flutter_facebook_auth: ^4.4.0
  sign_in_with_apple: ^4.0.0
  fluttertoast: ^8.0.9
  cached_network_image: ^3.2.1
  image_picker: ^0.8.5+3
  flutter_time_picker_spinner: ^2.0.0
  table_calendar: ^3.0.6
  flutter_spinkit: ^5.1.0
  carousel_slider: ^4.1.1
  modal_bottom_sheet: ^2.1.0
  package_info_plus: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: SUIT
      fonts:
        - asset: assets/fonts/SUIT-Medium.ttf
        - asset: assets/fonts/SUIT-Regular.ttf
          weight: 400
        - asset: assets/fonts/SUIT-Medium.ttf
          weight: 500
        - asset: assets/fonts/SUIT-Bold.ttf
          weight: 600