// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIB1di-O5eUgN-xpCdGxj6FimjzFlsGs4',
    appId: '1:985243073903:web:a405144d3dd88dda513c9a',
    messagingSenderId: '985243073903',
    projectId: 'onedaymate-b9037',
    authDomain: 'onedaymate-b9037.firebaseapp.com',
    storageBucket: 'onedaymate-b9037.appspot.com',
    measurementId: 'G-ZPDC0GMS8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4yWkRhZsR1JJMP2cODkujh6v98BtadSo',
    appId: '1:985243073903:android:ba3fef40adb43118513c9a',
    messagingSenderId: '985243073903',
    projectId: 'onedaymate-b9037',
    storageBucket: 'onedaymate-b9037.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXSDc88z_AFVBqCbv7UftLmcpeP8WnIsY',
    appId: '1:985243073903:ios:0d409e1af64742f1513c9a',
    messagingSenderId: '985243073903',
    projectId: 'onedaymate-b9037',
    storageBucket: 'onedaymate-b9037.appspot.com',
    iosClientId: '985243073903-0hau3dmvkv5gp643d091d7vl7h8i5qak.apps.googleusercontent.com',
    iosBundleId: 'com.hj.odm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXSDc88z_AFVBqCbv7UftLmcpeP8WnIsY',
    appId: '1:985243073903:ios:0d409e1af64742f1513c9a',
    messagingSenderId: '985243073903',
    projectId: 'onedaymate-b9037',
    storageBucket: 'onedaymate-b9037.appspot.com',
    iosClientId: '985243073903-0hau3dmvkv5gp643d091d7vl7h8i5qak.apps.googleusercontent.com',
    iosBundleId: 'com.hj.odm',
  );
}
